### PR TITLE
Fix the timeout problem

### PR DESCRIPTION
**Pull request by Shougo**
@zchee Please test it.

### CODE REVIEW

**Comment by zchee** [comment]
@Shougo I'll test it after the finished gocode pull request.
Sorry, wait a moment.

**Comment by zchee** [comment]
Ref: dump error message

```vim
[deoplete] Traceback (most recent call last):
[deoplete]   File "/usr/local/lib/python3.7/subprocess.py", line 405, in run
[deoplete]     stdout, stderr = process.communicate(input, timeout=timeout)
[deoplete]   File "/usr/local/lib/python3.7/subprocess.py", line 836, in communicate
[deoplete]     stdout, stderr = self._communicate(input, endtime, timeout)
[deoplete]   File "/usr/local/lib/python3.7/subprocess.py", line 1484, in _communicate
[deoplete]     self._check_timeout(endtime, orig_timeout)
[deoplete]   File "/usr/local/lib/python3.7/subprocess.py", line 864, in _check_timeout
[deoplete]     raise TimeoutExpired(self.args, orig_timeout)
[deoplete] subprocess.TimeoutExpired: Command '['zsh', '/Users/zchee/src/github.com/zchee/deoplete-zsh/bin/capture.zsh', '# s']' timed out after 0.5 seconds
[deoplete]
[deoplete] During handling of the above exception, another exception occurred:
[deoplete]
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/zchee/.cache/nvim/dein/.cache/init.vim/.dein/rplugin/python3/deoplete/deoplete.py", line 110, in gather_results
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]   File "/Users/zchee/src/github.com/zchee/deoplete-zsh/rplugin/python3/deoplete/sources/deoplete_zsh.py", line 36, in gather_candidates
[deoplete]     , timeout=0.5).splitlines()]:
[deoplete]   File "/usr/local/lib/python3.7/subprocess.py", line 336, in check_output
[deoplete]     **kwargs).stdout
[deoplete]   File "/usr/local/lib/python3.7/subprocess.py", line 410, in run
[deoplete]     stderr=stderr)
[deoplete] subprocess.TimeoutExpired: Command '['zsh', '/Users/zchee/src/github.com/zchee/deoplete-zsh/bin/capture.zsh', '# s']' timed out after 0.5 seconds
[deoplete] Could not get completions from: zsh.  Use :messages for error details.
```

**Comment by zchee** [comment]
@Shougo Sorry for a delay.
I'm not finished gocode fix...😱  but tested. It seems to solved error :)
Thanks, I'll merge.

**Comment by Shougo** [comment]
Thank you.

**Pull request merged**
